### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by gitzila** [openlumi/homeassistant_on_openwrt#22]
Hi, I tried your script on a NETGEAR R7800 (Nighthawk X4S AC2600) with 128 MB / 512 MB memory. But the script failed after some time when trying to create dir /usr/bin/hass with out of memory. Do you have any info about the consumed size of the full installation of home assistant and where the memory is needed? Maybe its just about some megabytes I could possibly free up before the next try.

**Comment by devbis** [comment]
I tried to install on a 128MB router and had to run the part to download and compress home assistant itself and its frontend on a bigger machine https://github.com/openlumi/homeassistant_on_openwrt/blob/21.02/ha_install.sh#L273-L538 and then copy with SCP to the router. It can probably help you as well. 
I don't know about the requirements for memory because it varies from version to version.

**Comment by gitzila** [comment]
Thanks a lot for the hint. I'll test it and give feedback.
