### ISSUE TITLE
Bundle and publish as official opkg

### ISSUE THREAD

**Issue by marfier** [openlumi/homeassistant_on_openwrt#24]
Hello,

Are you considering to bundle and publish this into an official opkg package so that anyone can easily find it and use it?

It seems to fulfill all the requirements, like having a init daemon to easily manage the application.

Thank you for the very useful script!

**Comment by devbis** [comment]
Hi! Thank you for the idea! 
I don't think that the script is good enough for packing it into opkg, because it is a set of "hacks" to run HA on openwrt libraries. 

For full packages you can review these projects: 

- https://github.com/lmahmutov/SGW-Homeassistant
- https://github.com/The-BB/homeassistant
